version: '3'

networks:
  net_private:
    driver: bridge
    ipam:
      config:
        - subnet: <%= CIDR %>

services:
  <% AUTOGEN_CIDRS.split(",").forEach(function(cidr,i){ %>

  hashgraph<%= i %>:
    #Dockerfile in current dir:
    build: .
    # volumes:
    #   - './sdk.gradle/build:/usr/src/app/sdk.gradle'
    #   - './sdk:/usr/src/app/sdk'
    ports:
      - '<%= Number(PORT_BASE_INT) %>:<%= Number(PORT_BASE_EXT) %>'
      - '<%= Number(PORT_BASE_INT)+Number(TELNET_PORT_OFFSET) %>:<%= Number(PORT_BASE_INT)+Number(TELNET_PORT_OFFSET) %>'
    env_file:
      - .env
    networks:
      net_private:
        ipv4_address: <%= cidr %>
  <% }) %>
